import 'package:flutter/material.dart';
import '../../core/localization/app_language.dart';
import '../../core/theme/app_colors.dart';
import 'settings_detail_screens.dart';

class AccountSettingsScreen extends StatefulWidget { const AccountSettingsScreen({super.key, required this.isCompany}); final bool isCompany; @override State<AccountSettingsScreen> createState() => _AccountSettingsScreenState(); }
class _AccountSettingsScreenState extends State<AccountSettingsScreen> {
  bool jobUpdates = true, applicationUpdates = true, emailUpdates = false;
  @override Widget build(BuildContext context) => ValueListenableBuilder<Locale>(valueListenable: AppLanguage.locale, builder: (_, locale, __) => Scaffold(backgroundColor: AppColors.bg, appBar: AppBar(centerTitle: true, title: Text(AppLanguage.t('settings'), style: const TextStyle(color: AppColors.navy, fontSize: 18, fontWeight: FontWeight.w800)), leading: IconButton(onPressed: () => Navigator.pop(context), icon: const Icon(Icons.arrow_back_ios_new_rounded, size: 18))), body: SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(20, 14, 20, 32), children: [
    _Card(title: AppLanguage.t('profile'), child: _Row(icon: Icons.person_outline_rounded, title: AppLanguage.t('updateProfile'), onTap: () => _go(const UpdateProfileScreen(isCompany: false)))), const SizedBox(height: 14),
    _Card(title: AppLanguage.t('notifications'), child: Column(children: [_Switch(title: widget.isCompany ? 'Job activity' : AppLanguage.t('jobUpdates'), value: jobUpdates, onChanged: (v) => setState(() => jobUpdates = v)), const Divider(color: AppColors.cardBorder), _Switch(title: AppLanguage.t('applicationUpdates'), value: applicationUpdates, onChanged: (v) => setState(() => applicationUpdates = v)), const Divider(color: AppColors.cardBorder), _Switch(title: AppLanguage.t('emailUpdates'), value: emailUpdates, onChanged: (v) => setState(() => emailUpdates = v))])), const SizedBox(height: 14),
    _Card(title: AppLanguage.t('account'), child: Column(children: [_Row(icon: Icons.lock_outline_rounded, title: AppLanguage.t('changePassword'), onTap: () => _go(const ChangePasswordScreen())), const Divider(color: AppColors.cardBorder), _Row(icon: Icons.privacy_tip_outlined, title: AppLanguage.t('privacy'), onTap: () => _go(const PrivacyScreen())), const Divider(color: AppColors.cardBorder), _Row(icon: Icons.language_rounded, title: AppLanguage.t('language'), subtitle: {'ar': 'العربية', 'de': 'Deutsch'}[locale.languageCode] ?? 'English', onTap: () => _go(const LanguageScreen()))])), const SizedBox(height: 14),
    _Card(title: AppLanguage.t('about'), child: _Row(icon: Icons.info_outline_rounded, title: AppLanguage.t('about'), subtitle: 'TOTOTL INTGRX · 1.0.0', onTap: () => _go(const AboutScreen()))),
  ]))));
  void _go(Widget screen) => Navigator.push(context, MaterialPageRoute(builder: (_) => screen));
}
class _Card extends StatelessWidget { const _Card({required this.title, required this.child}); final String title; final Widget child; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(17), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(18), border: Border.all(color: AppColors.cardBorder)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(color: AppColors.navy, fontSize: 16, fontWeight: FontWeight.w800)), const SizedBox(height: 8), child])); }
class _Switch extends StatelessWidget { const _Switch({required this.title, required this.value, required this.onChanged}); final String title; final bool value; final ValueChanged<bool> onChanged; @override Widget build(BuildContext context) => SwitchListTile(contentPadding: EdgeInsets.zero, title: Text(title, style: const TextStyle(color: AppColors.navy, fontWeight: FontWeight.w700)), value: value, activeColor: AppColors.primary, onChanged: onChanged); }
class _Row extends StatelessWidget { const _Row({required this.icon, required this.title, required this.onTap, this.subtitle}); final IconData icon; final String title; final String? subtitle; final VoidCallback onTap; @override Widget build(BuildContext context) => InkWell(onTap: onTap, borderRadius: BorderRadius.circular(12), child: Padding(padding: const EdgeInsets.symmetric(vertical: 10), child: Row(children: [Icon(icon, color: AppColors.blue, size: 20), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(color: AppColors.navy, fontWeight: FontWeight.w700)), if (subtitle != null) ...[const SizedBox(height: 2), Text(subtitle!, style: const TextStyle(color: AppColors.grey, fontSize: 11.5))]])), const Icon(Icons.chevron_right_rounded, color: AppColors.lightGrey)]))); }
